force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <description>Total Price</description>
    <label>Total Price</label>
    <summarizedField>Contract_Line_Item__c.Subtotal_Price__c</summarizedField>
    <summaryForeignKey>Contract_Line_Item__c.Contract__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <description>custom Contract Line Item</description>
    <label>Contract Line Item</label>
    <nameField>
        <displayFormat>CRP-{0000}</displayFormat>
        <label>Contract Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Line_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Line Items</relationshipLabel>
    <relationshipName>Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Quantity</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Subtotal_Price__c.field-meta.xml
<CustomField>
    <fullName>Subtotal_Price__c</fullName>
    <formula>Quantity__c *  Unit_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subtotal Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Unit Price</description>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ContractPDFcontroller.cls
public with sharing class ContractPDFcontroller {
  public Id recordId {get; set;}
  public Contract contract {get; set;}

  public ContractPDFcontroller(ApexPages.StandardController controller) {
    if (controller!=null) {
      recordId = controller.getId();
      contract = (Contract) controller.getRecord();
    }
  }

  public ContractPDFcontroller(Id recordId) {
    this.recordId = recordId;
    contract = queryContract(recordId);
  }

  public ContractPDFcontroller(Contract contract) {
    recordId = contract.Id;
    this.contract = contract;
  }

  public ContractPDFcontroller() {
    if (ApexPages.currentPage().getParameters().containsKey('id')) {
      recordId = ApexPages.currentPage().getParameters().get('id');
      contract = queryContract(recordId);
    }
  }

  public static Contract queryContract(Id contractId) {
    if (String.isBlank(contractId)) return null;

    return [
      SELECT Id
        ,ContractNumber
        ,AccountId
        ,Account.Name
        ,CompanySignedId
        ,CompanySigned.Name
        ,CompanySignedDate
        ,CustomerSignedId
        ,CustomerSigned.Name
        ,CustomerSignedDate
        ,StartDate
        ,EndDate
        ,ContractTerm
        ,Description
        ,Opportunity__c
        ,Opportunity__r.Name
        ,Pricebook2Id
        ,SpecialTerms
        ,Status
        ,Total_Price__c
        ,(SELECT Id
          ,Name
          ,Description__c
          ,Opportunity__c
          ,Product__c
          ,Product__r.Name
          ,Quantity__c
          ,Unit_Price__c
          ,Subtotal_Price__c
        FROM Contract_Line_Items__r)
      FROM Contract
      WHERE Id = :contractId
      LIMIT 1
    ];
  }
}